// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    flip
    (
        flip
        flipBounty
        getOwnerPercentFees
        getBountyAmount
        getMaximumBet
        getMaximumBetPercent
        getMinimumBlockBounty
        getTokenReserve
        flipForId
        getLastFlipId
        getLastBountyFlipId
        increaseReserve
        withdrawReserve
        setMaximumBetPercent
        setMaximumBet
        setMinimumBlockBounty
    )
}

elrond_wasm_node::wasm_empty_callback! {}
